clone_mirror: refuse to clone from self
When running something like this:
```
tiup mirror clone /tmp/tidb_mirror -a amd64 --prefix v5.1.0 --os linux
tiup mirror set /tmp/tidb_mirror
tiup mirror clone /tmp/tidb_mirror -a amd64 --prefix v5.1.0 --os linux
```
This results in metadata being changed/corrupted.

Then the next `tiup mirror clone ...` results in:
```
Error: read manifest from mirror(/tmp/tidb_mirror) failed: not enough signatures (0) for threshold 1 in timestamp.json
```

This can easily be fixed with `tiup mirror set ...`, but it is best to
avoid this. And also cloning from self is probably not what the user
wanted in the first place. So adding the source to the output to make
this easier to spot.

Related: https://tidbcommunity.slack.com/archives/C019S7HLP61/p1625059913130200