Fix compilation errors with gopsutil v4.25.2 library
As the golang-github-shirou-gopsutil-dev package v4.25.2 in Debian is
newer than the v3.21.11 in go.mod of TiUP, the Debian build failed on:

    src/github.com/pingcap/tiup/pkg/insight/process.go:165:24: cannot use proc.Status() (value of type []string) as string value in assignment
    src/github.com/pingcap/tiup/pkg/insight/process_linux.go:24:38: undefined: process.ClockTicks

Apply these changes on TiUP to make it compatible:

- The `proc.Status()` method now returns a slice of strings (`[]string`)
  instead of a single string. Update the assignment to take the first
  element of the slice, assuming it contains the primary status
  information. Add a check for an empty slice to prevent panics.

- The `process.ClockTicks` constant and the related logic for parsing
  `/proc/[pid]/stat` are no longer supported. Replace this with a call
  to `proc.CreateTime()`, which provides the process creation time in
  milliseconds since the Unix epoch. Convert this value to seconds for
  the `StartTime` field.

Additionally, remove unused import statements to avoid failures on:

    src/github.com/pingcap/tiup/pkg/insight/process_linux.go:8:2: "os" imported and not used
    src/github.com/pingcap/tiup/pkg/insight/process_linux.go:9:2: "strconv" imported and not used
    src/github.com/pingcap/tiup/pkg/insight/process_linux.go:10:2: "strings" imported and not used